[[redirects]]
  from = "/auth/*"
  to = "https://bondify-1lzw.onrender.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/user/*"
  to = "https://bondify-1lzw.onrender.com/user/:splat"
  status = 200
  force = true
